# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Paul's tools and stuff
email: paul@paulgoesdeep.com
description: >- # this means to ignore newlines until "baseurl:"
  A small library of commands, scripts and cheatsheets for a number of technologies
  I've been working or playing around with
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: ""
github_username:  velll

# Build settings
theme: minima

header_pages:
  - about.md

chapters:
  - title: "Oracle DB development"
    dir: "/oracle/dev/"
  - title: "Ruby"
    dir: "/ruby/"
  - title: JS
    dir: '/js/'
  - title: CSS
    dir: '/css/'
  - title: Rails
    dir: '/rails/'
  - title: Docker
    dir: '/docker/'
  - title: 'Regular expressions'
    dir: "/regex/"
  - title: 'Mongo DB'
    dir: "/mongo/"
  - title: "Oracle DB administration"
    dir: "/oracle/dba/"
  - title: 'PostgreSQL'
    dir: "/postgresql/"
  - title: "Python"
    dir: "/python/"
  - title: "SSH"
    dir: "/ssh/"
  - title: "Nginx"
    dir: "/nginx/"
  - title: GIT
    dir: '/git/'
  - title: FFmpeg
    dir: '/ffmpeg/'
  - title: "Linux"
    dir: "/linux/"

defaults:
  - scope:
      path: "**/*"
    values:
      layout: page


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
